### ISSUE TITLE
[BUG] Settings reset when log out > log in.

### ISSUE THREAD

**Issue by Romsh** [Karl-HeinzSchneider/WoW-Details-Skin-TheWarWithin#6]
**Describe the bug**
When reloading the settings get back to default. I want to have a upside down setup (title bar at the bottom) but it keeps reseting to default. 
PS : Can we have the title bar skin working for the bottom version too ? I need to hide it to make it works

**Versions (please complete the following information):**

- WoW: Retails (TWW)

**Comment by Romsh** [comment]
Didn't know about the "/tww import". Sorry

**Comment by Karl-HeinzSchneider** [comment]
Details skins are a bit strange, thats why I added the import option. Does this fix it for you?

**Comment by Romsh** [comment]
Yes. I had to redo my settings but it works fine now. Ty

**Comment by Karl-HeinzSchneider** [comment]
Thanks for the info!
